### ISSUE TITLE
TLS Support for Server?

### ISSUE THREAD

**Issue by cal-jlab** [dCache/xrootd4j#179]
Hi, can someone explain the status of server TLS support?  I've been trying to figure out by studying the code how I can enable TLS on my (modified) standalone server.  I'd appreciate any tips on offer.

Thanks!

**Comment by cal-jlab** [comment]
I created a subclass of SSLHandlerFactory, added an instance to the TLSSessionInfo, set the flags to TLS optional, but now I am getting handshake timeouts reported at my server, and socket errors at the xrdcp client.

**Comment by DmitryLitvintsev** [comment]
May be you could post a pointer to your codd and attach error log. Sorry for slow responding it has been a busy month (and the next month seems busy too). But we will try to help.

**Comment by cal-jlab** [comment]
Hi Dmitry!  Thanks for your response.  My code is not on github, but following are the handler class, and the bit where I configure the session:

```
public class MySSLHandlerFactory extends SSLHandlerFactory {
    @Override
    protected Supplier<SslContext> buildContextSupplier(Properties properties) throws Exception {
        try (InputStream cert = Jasmine.class.getClassLoader().getResourceAsStream("sca2302-cert.pem");
                InputStream key = Jasmine.class.getClassLoader().getResourceAsStream("tk-rsa-pkcs8.pem"))
        {
            SslContext sslContext;
            if (startTls) {
                sslContext = SslContextBuilder.forServer(cert, key).build();
            }
            else {
                sslContext = SslContextBuilder.forClient().build();
            }
            return () -> sslContext;
        }
    }
}

```
        SigningPolicy signingPolicy = new SigningPolicy();
        ServerProtocolFlags flags = new ServerProtocolFlags(kXR_haveTLS);
        TLSSessionInfo tlsSessionInfo = new TLSSessionInfo(flags);
        var sslhandler = new MySSLHandlerFactory();
        sslhandler.initialize(System.getProperties(), true);
        tlsSessionInfo.setServerSslHandlerFactory(sslhandler);

        XrootdSessionHandler sessionHandler = new XrootdSessionHandler();
        /*
         * Support security level/signed hash verification or for TLS.
         */
        sessionHandler.setTlsSessionInfo(tlsSessionInfo);
        sessionHandler.setSigningPolicy(signingPolicy);
        pipeline.addLast(XrootdSessionHandler.SESSION_HANDLER, sessionHandler);


Here's the debug log:

```
[2024-05-21 15:14:16,632] DEBUG (nioEventLoopGroup-3-3) XrootdService.java:69 - adding org.dcache.xrootd.core.XrootdAuthenticationHandler@18efeedf to org.dcache.xrootd.core.XrootdSessionHandler@34a2d357.
[2024-05-21 15:14:16,632] DEBUG (nioEventLoopGroup-3-3) AbstractInternalLogger.java:145 - [id: 0x940e1a32, L:/127.0.0.1:10940 - R:/127.0.0.1:58828] REGISTERED
[2024-05-21 15:14:16,632] DEBUG (nioEventLoopGroup-3-3) AbstractInternalLogger.java:145 - [id: 0x940e1a32, L:/127.0.0.1:10940 - R:/127.0.0.1:58828] ACTIVE
[2024-05-21 15:14:16,633] DEBUG (nioEventLoopGroup-3-3) AbstractInternalLogger.java:145 - [id: 0x940e1a32, L:/127.0.0.1:10940 - R:/127.0.0.1:58828] READ: org.dcache.xrootd.protocol.messages.ProtocolRequest@7aa15508
[2024-05-21 15:14:16,633] DEBUG (nioEventLoopGroup-3-3) AbstractInternalLogger.java:145 - [id: 0x940e1a32, L:/127.0.0.1:10940 - R:/127.0.0.1:58828] WRITE: protocol-response[-1][(secLvl 0)(overrides {})(force false)]
[2024-05-21 15:14:16,633] DEBUG (nioEventLoopGroup-3-3) AbstractInternalLogger.java:145 - [id: 0x940e1a32, L:/127.0.0.1:10940 - R:/127.0.0.1:58828] FLUSH
[2024-05-21 15:14:16,633] DEBUG (nioEventLoopGroup-3-3) AbstractInternalLogger.java:145 - [id: 0x940e1a32, L:/127.0.0.1:10940 - R:/127.0.0.1:58828] READ COMPLETE
[2024-05-21 15:14:16,633] DEBUG (nioEventLoopGroup-3-3) AbstractInternalLogger.java:145 - [id: 0x940e1a32, L:/127.0.0.1:10940 - R:/127.0.0.1:58828] READ COMPLETE
[2024-05-21 15:14:26,643] DEBUG (nioEventLoopGroup-3-3) AbstractInternalLogger.java:145 - [id: 0x940e1a32, L:/127.0.0.1:10940 - R:/127.0.0.1:58828] USER_EVENT: SslHandshakeCompletionEvent(io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms)
[2024-05-21 15:14:26,644] DEBUG (nioEventLoopGroup-3-3) AbstractInternalLogger.java:99 - [id: 0x940e1a32, L:/127.0.0.1:10940 ! R:/127.0.0.1:58828] EXCEPTION: org.dcache.xrootd.core.XrootdException: SSL failure on channel ([id: 0x940e1a32, L:/127.0.0.1:10940 ! R:/127.0.0.1:58828]), session token (null), caused by (han
dshake timed out after 10000ms: root cause io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms).
org.dcache.xrootd.core.XrootdException: SSL failure on channel ([id: 0x940e1a32, L:/127.0.0.1:10940 ! R:/127.0.0.1:58828]), session token (null), caused by (handshake timed out after 10000ms: root cause io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms).
        at org.dcache.xrootd.core.AbstractXrootdDecoder.createException(AbstractXrootdDecoder.java:95) ~[xrootd4j-4.6.1-SNAPSHOT.jar:4.6.1-SNAPSHOT]
        at org.dcache.xrootd.core.AbstractXrootdDecoder.exceptionCaught(AbstractXrootdDecoder.java:115) ~[xrootd4j-4.6.1-SNAPSHOT.jar:4.6.1-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.handler.ssl.SslHandler.exceptionCaught(SslHandler.java:1203) ~[netty-handler-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:69) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:65) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:57) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:31) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:57) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:31) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.AbstractCoalescingBufferQueue.releaseAndCompleteAll(AbstractCoalescingBufferQueue.java:360) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.AbstractCoalescingBufferQueue.releaseAndFailAll(AbstractCoalescingBufferQueue.java:218) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.handler.ssl.SslHandler.releaseAndFailAll(SslHandler.java:2007) ~[netty-handler-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.handler.ssl.SslHandler.access$2300(SslHandler.java:170) ~[netty-handler-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2220) ~[netty-handler-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by cal-jlab** [comment]
I added debug logging, so here's some more info:

```
2024-05-21 16:49:41,106 DEBUG nioEventLoopGroup-3-1 - OpenSsl.java                    444 - Supported protocols (OpenSSL): [SSLv2Hello, TLSv1, TLSv1.1, TLSv1.2, TLSv1.3] 
2024-05-21 16:49:41,106 DEBUG nioEventLoopGroup-3-1 - OpenSsl.java                    445 - Default cipher suites (OpenSSL): [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_S
HA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256]
2024-05-21 16:49:41,158 DEBUG nioEventLoopGroup-3-1 - ResourceLeakDetectorFactory.java  196 - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@4331338b
2024-05-21 16:49:42,533 DEBUG nioEventLoopGroup-3-1 - XrootdSessionHandler.java       144 - XrootdSessionHandler.getResponse: Request kXR_protocol
2024-05-21 16:49:42,534 DEBUG nioEventLoopGroup-3-1 - XrootdProtocolRequestHandler.java   58 - doOnProtocolRequest, version 1297, expect 3, option 15.
2024-05-21 16:49:42,534 DEBUG nioEventLoopGroup-3-1 - TLSSessionInfo.java             684 - setLocalTlsActivation 1297, 3, 15.
2024-05-21 16:49:42,534 DEBUG nioEventLoopGroup-3-1 - TLSSessionInfo.java             171 - Client version 1297, options 15, expect 3.
2024-05-21 16:49:42,534 DEBUG nioEventLoopGroup-3-1 - TLSSessionInfo.java             234 - Client kXR_wantTLS.
2024-05-21 16:49:42,534 DEBUG nioEventLoopGroup-3-1 - TLSSessionInfo.java             237 - setLocalTlsActivation, activation is now LOGIN.
2024-05-21 16:49:42,535 DEBUG nioEventLoopGroup-3-1 - TLSSessionInfo.java             662 - server uses TLS ? true.
2024-05-21 16:49:42,536 DEBUG nioEventLoopGroup-3-1 - TLSSessionInfo.java             347 - transitionedToTLS, server tlsActivation: LOGIN.
2024-05-21 16:49:42,539 DEBUG nioEventLoopGroup-3-1 - ResourceLeakDetectorFactory.java  196 - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@288cfe2e
2024-05-21 16:49:42,545 DEBUG nioEventLoopGroup-3-1 - TLSSessionInfo.java             387 - PIPELINE addFirst:  SSLHandler need auth false, want auth false.
2024-05-21 16:49:42,545 DEBUG nioEventLoopGroup-3-1 - TLSSessionInfo.java             655 - server transitioned to TLS ? true.
2024-05-21 16:49:42,546 DEBUG nioEventLoopGroup-3-1 - XrootdProtocolRequestHandler.java   73 - kXR_protocol, server has now transitioned to tls? true.
2024-05-21 16:49:42,546 DEBUG nioEventLoopGroup-3-1 - XrootdProtocolRequestHandler.java   77 - Sending protocol message with server flags mode: OPTIONAL, flags: -1006632960 (manager false, meta-server false, proxy-server false, server false, supervisor false, data-server false, load-balancer true, tlsData false, tlsG
PF false, tlsLogin true, tlsSession false, tlsTPC false, goToTLS true, anonGPF false), signing policy (secLvl 0)(overrides {})(force false).
2024-05-21 16:49:52,555 WARN  nioEventLoopGroup-3-1 - TLSSessionInfo.java              73 - Server: TLS handshake failed: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms.
2024-05-21 16:49:52,556 ERROR nioEventLoopGroup-3-1 - XrootdRequestHandler.java       172 - TLS handshake failed: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms.
2024-05-21 16:49:52,557 ERROR nioEventLoopGroup-3-1 - AbstractXrootdDecoder.java       94 - SSL failure on channel ([id: 0x5f78b979, L:/127.0.0.1:10940 ! R:/127.0.0.1:52876]), session token (null), caused by (handshake timed out after 10000ms: root cause io.netty.handler.ssl.SslHandshakeTimeoutException: handshake ti
med out after 10000ms).
2024-05-21 16:49:52,558 WARN  nioEventLoopGroup-3-1 - DataServerHandler.java          132 - org.dcache.xrootd.core.XrootdException: SSL failure on channel ([id: 0x5f78b979, L:/127.0.0.1:10940 ! R:/127.0.0.1:52876]), session token (null), caused by (handshake timed out after 10000ms: root cause io.netty.handler.ssl.Ss
lHandshakeTimeoutException: handshake timed out after 10000ms).
2024-05-21 16:49:52,584 DEBUG nioEventLoopGroup-3-2 - XrootdSessionHandler.java       144 - XrootdSessionHandler.getResponse: Request kXR_protocol
2024-05-21 16:49:52,584 DEBUG nioEventLoopGroup-3-2 - XrootdProtocolRequestHandler.java   58 - doOnProtocolRequest, version 1297, expect 3, option 15.
2024-05-21 16:49:52,584 DEBUG nioEventLoopGroup-3-2 - TLSSessionInfo.java             684 - setLocalTlsActivation 1297, 3, 15.
2024-05-21 16:49:52,584 DEBUG nioEventLoopGroup-3-2 - TLSSessionInfo.java             171 - Client version 1297, options 15, expect 3.
2024-05-21 16:49:52,584 DEBUG nioEventLoopGroup-3-2 - TLSSessionInfo.java             234 - Client kXR_wantTLS.
2024-05-21 16:49:52,584 DEBUG nioEventLoopGroup-3-2 - TLSSessionInfo.java             237 - setLocalTlsActivation, activation is now LOGIN.
2024-05-21 16:49:52,584 DEBUG nioEventLoopGroup-3-2 - TLSSessionInfo.java             662 - server uses TLS ? true.
2024-05-21 16:49:52,584 DEBUG nioEventLoopGroup-3-2 - TLSSessionInfo.java             347 - transitionedToTLS, server tlsActivation: LOGIN.
2024-05-21 16:49:52,585 DEBUG nioEventLoopGroup-3-2 - TLSSessionInfo.java             387 - PIPELINE addFirst:  SSLHandler need auth false, want auth false.
2024-05-21 16:49:52,585 DEBUG nioEventLoopGroup-3-2 - TLSSessionInfo.java             655 - server transitioned to TLS ? true.
2024-05-21 16:49:52,585 DEBUG nioEventLoopGroup-3-2 - XrootdProtocolRequestHandler.java   73 - kXR_protocol, server has now transitioned to tls? true.
2024-05-21 16:49:52,585 DEBUG nioEventLoopGroup-3-2 - XrootdProtocolRequestHandler.java   77 - Sending protocol message with server flags mode: OPTIONAL, flags: -1006632960 (manager false, meta-server false, proxy-server false, server false, supervisor false, data-server false, load-balancer true, tlsData false, tlsG
PF false, tlsLogin true, tlsSession false, tlsTPC false, goToTLS true, anonGPF false), signing policy (secLvl 0)(overrides {})(force false).
2024-05-21 16:49:53,941 WARN  nioEventLoopGroup-3-2 - TLSSessionInfo.java              73 - Server: TLS handshake failed: java.nio.channels.ClosedChannelException.
2024-05-21 16:49:53,942 INFO  nioEventLoopGroup-3-2 - DataServerHandler.java          127 - Connection closed

```

**Comment by cal-jlab** [comment]
I tried to figure out how to enable SSL by studying the dcache code, but so far have been unable to understand it.  I wonder what the purpose is of the class TLSHandlerProvider.  It appears that dcache loads SSL support via plugin?  It's not really clear.

**Comment by cal-jlab** [comment]
To simplify matters, I tried adding TLS support to the stock standalone server using the same code displayed above, with the same effect.  I enabled javax.net.debug=all, but it doesn't reveal anything more: just lots of "HandshakeContext.java:297|Ignore unsupported cipher suite:" messages.

**Comment by cal-jlab** [comment]
Also verified same behavior whether using OpenSSL or JDK provider.

**Comment by cal-jlab** [comment]
Stepping through xrdcp in debugger, it appears that the protocol response is never received, like the server is transitioning to SSL before sending the response?

**Comment by cal-jlab** [comment]
In wireshark, I see that the xrdcp client has piggybacked the protocol request along with the initial handshake.  The server responds to the handshake with the expected 16-byte response, but then the very next packet from the server is a FIN-ACK, closing the socket, after which there is no further communication.
![image](https://github.com/dCache/xrootd4j/assets/67376285/0bbf33a5-f214-446f-8bbf-405d3470b86a)

**Comment by cal-jlab** [comment]
I found that I needed to set startTLS on the newly built context.  Doing this, the client does receive the protocol response, but now I have a "connection refused" error from the client.  So there is still something amiss with the SSL connection, but it's not clear what.

**Comment by cal-jlab** [comment]
One step closer: I had to set $X509_CERT_DIR to get past the "connection refused" error, which was caused by lack of cert.  Now the client is reporting "[FATAL] TLS error: resource temporarily unavailable."

**Comment by cal-jlab** [comment]
At the server, when using OpenSSL provider I see the following error message:

`io.netty.handler.ssl.ReferenceCountedOpenSslEngine$OpenSslHandshakeException: error:10000070:SSL routines:OPENSSL_internal:BAD_PACKET_LENGTH.`

And when using JDK provider: 

```
Fatal (HANDSHAKE_FAILURE): Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16) (
"throwable" : {
  javax.crypto.BadPaddingException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)
        at sun.security.ssl.SSLCipher$T13GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1845)
        at sun.security.ssl.SSLEngineInputRecord.decodeInputRecord(SSLEngineInputRecord.java:240)
        at sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:197)
        at sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:160)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109)
        at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:588)
        at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:544)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:411)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:390)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:626)
        at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:309)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1441)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1334)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1383)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)}

)
11:45:45.578 [nioEventLoopGroup-3-1] WARN  o.d.xrootd.security.TLSSessionInfo - Server: TLS handshake failed: javax.net.ssl.SSLHandshakeException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16).
11:45:45.579 [nioEventLoopGroup-3-1] DEBUG o.d.x.s.DataServerChannelInitializer - [id: 0x86af1e01, L:/129.57.89.39:1094 - R:/129.57.89.39:34122] USER_EVENT: SslHandshakeCompletionEvent(javax.net.ssl.SSLHandshakeException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16))
11:45:45.579 [nioEventLoopGroup-3-1] ERROR o.d.xrootd.core.XrootdRequestHandler - TLS handshake failed: javax.net.ssl.SSLHandshakeException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16).
javax.net.ssl|WARNING|0F|nioEventLoopGroup-3-1|2024-05-23 11:45:45.581 EDT|SSLEngineOutputRecord.java:168|outbound has closed, ignore outbound application data
```

**Comment by cal-jlab** [comment]
Problem(s) solved!  My final remaining issue had to do with a missing certificate chain.  It's working now :-)

**Comment by kofemann** [comment]
@cal-jlab I am glad that you have sorted it out. I have updated our standalone server to provide a basic demo of how to use TLS with xrootd4j

https://rb.dcache.org/r/14264/diff/1/#2

**Comment by cal-jlab** [comment]
Cool!  Thanks :-)
