### ISSUE TITLE
possible race in get checksum

### ISSUE THREAD

**Issue by alrossi** [dCache/xrootd4j#9]
Not sure if this is xrootd4j or dcache-xrootd, so posting in both places

When running multiple backgrounded transfers on my desktop, I encountered:

[1.203GB/2.051GB][ 58%][=============================>                    ][6.099MB/s]
Run: [ERROR] Server responded with an error: [3012] Internal server error (ChecksumChannel must not be written to after getChecksums)

This is with two-party write from the client to the pool.

**Comment by alrossi** [comment]
Also saw it with TPC:

```
29 Mar 2019 11:38:58 (dmsdca19-1) [] Uncaught exception in thread xrootd-tpc-client-1
java.lang.IllegalStateException: ChecksumChannel must not be written to after getChecksums
        at com.google.common.base.Preconditions.checkState(Preconditions.java:504) ~[guava-24.1-jre.jar:na]
        at org.dcache.pool.movers.ChecksumChannel.write(ChecksumChannel.java:164) ~[dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.pool.repository.ForwardingRepositoryChannel.write(ForwardingRepositoryChannel.java:46) ~[dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.pool.repository.inotify.InotifyChannel.write(InotifyChannel.java:145) ~[dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.pool.repository.ForwardingRepositoryChannel.write(ForwardingRepositoryChannel.java:46) ~[dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.pool.repository.AllocatorAwareRepositoryChannel.write(AllocatorAwareRepositoryChannel.java:183) ~[dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.pool.movers.MoverChannel.write(MoverChannel.java:171) ~[dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.pool.movers.MoverChannelDecorator.write(MoverChannelDecorator.java:85) ~[dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.xrootd.pool.WriteDescriptor.write(WriteDescriptor.java:41) ~[dcache-xrootd-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.xrootd.tpc.TpcWriteDescriptor.write(TpcWriteDescriptor.java:333) ~[dcache-xrootd-5.1.0-SNAPSHOT.jar:3.5.0-SNAPSHOT]
        at org.dcache.xrootd.tpc.TpcSourceReadHandler.doOnReadResponse(TpcSourceReadHandler.java:124) ~[xrootd4j-3.5.0-SNAPSHOT.jar:3.5.0-SNAPSHOT]
        at org.dcache.xrootd.tpc.AbstractClientRequestHandler.responseReceived(AbstractClientRequestHandler.java:509) [xrootd4j-3.5.0-SNAPSHOT.jar:3.5.0-SNAPSHOT]
        at org.dcache.xrootd.tpc.AbstractClientRequestHandler.channelRead(AbstractClientRequestHandler.java:78) [xrootd4j-3.5.0-SNAPSHOT.jar:3.5.0-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at org.dcache.xrootd.tpc.AbstractClientRequestHandler.doOnReadResponse(AbstractClientRequestHandler.java:238) [xrootd4j-3.5.0-SNAPSHOT.jar:3.5.0-SNAPSHOT]
        at org.dcache.xrootd.tpc.AbstractClientRequestHandler.responseReceived(AbstractClientRequestHandler.java:509) [xrootd4j-3.5.0-SNAPSHOT.jar:3.5.0-SNAPSHOT]
        at org.dcache.xrootd.tpc.AbstractClientRequestHandler.channelRead(AbstractClientRequestHandler.java:78) [xrootd4j-3.5.0-SNAPSHOT.jar:3.5.0-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at org.dcache.xrootd.tpc.AbstractClientRequestHandler.doOnReadResponse(AbstractClientRequestHandler.java:238) [xrootd4j-3.5.0-SNAPSHOT.jar:3.5.0-SNAPSHOT]
        at org.dcache.xrootd.tpc.AbstractClientRequestHandler.responseReceived(AbstractClientRequestHandler.java:509) [xrootd4j-3.5.0-SNAPSHOT.jar:3.5.0-SNAPSHOT]
        at org.dcache.xrootd.tpc.AbstractClientRequestHandler.channelRead(AbstractClientRequestHandler.java:78) [xrootd4j-3.5.0-SNAPSHOT.jar:3.5.0-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-codec-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [netty-codec-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.10.Final.jar:4.1.10.Final]
        at org.dcache.util.CDCThreadFactory.lambda$newThread$0(CDCThreadFactory.java:50) [dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.dcache.util.CDCThreadFactory$$Lambda$219/874061582.run(Unknown Source) [dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by alrossi** [comment]
By adding this code to the pool request handler's ``doOnWrite`` method

```
           new Thread(() -> {
                try {
                    Thread.sleep(20);
                    descriptor.getChannel().release();  // FIXME GET RID OF THIS!!!!
                } catch (InterruptedException e) {

                }
            }).start();
            descriptor.write(msg);
```

I can reproduce this.  

```
[arossi@fndcatemp2 ~]$ xrdcp500 -C adler32 data/data_1GB xroot://dmsdca18.fnal.gov:1097//pnfs/fs/usr/test/arossi/scratch/tls-off/data_1GB-0
[8MB/1.025GB][  0%][>                                                 ][4MB/s]  
Run: [ERROR] Server responded with an error: [3012] Internal server error (ChecksumChannel must not be written to after getChecksums) (destination)
```

This suggests that added synchronization is necessary.

**Comment by alrossi** [comment]
Yes.   Looking at these stack traces:

```
java.lang.Throwable: finalizeChecksums
        at org.dcache.pool.movers.ChecksumChannel.finalizeChecksums(ChecksumChannel.java:257)
        at org.dcache.pool.movers.ChecksumChannel.getChecksums(ChecksumChannel.java:246)
        at org.dcache.pool.movers.AbstractMover.getActualChecksums(AbstractMover.java:348)
        at org.dcache.pool.classic.DefaultPostTransferService.lambda$execute$1(DefaultPostTransferService.java:108)
        at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:31)
        at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:149)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
19 May 2020 13:31:16 (dmsdca15-OFF) [] xrootd server error while processing write[handle=0,offset=8388608,length=8388608] (please report this to support@dcache.org)
java.lang.IllegalStateException: ChecksumChannel must not be written to after getChecksums
        at com.google.common.base.Preconditions.checkState(Preconditions.java:504)
        at org.dcache.pool.movers.ChecksumChannel.write(ChecksumChannel.java:164)
        at org.dcache.pool.repository.ForwardingRepositoryChannel.write(ForwardingRepositoryChannel.java:46)
        at org.dcache.pool.repository.inotify.InotifyChannel.write(InotifyChannel.java:151)
        at org.dcache.pool.repository.ForwardingRepositoryChannel.write(ForwardingRepositoryChannel.java:46)
        at org.dcache.pool.repository.AllocatorAwareRepositoryChannel.write(AllocatorAwareRepositoryChannel.java:188)
        at org.dcache.pool.movers.MoverChannel.write(MoverChannel.java:171)
        at org.dcache.pool.movers.MoverChannelDecorator.write(MoverChannelDecorator.java:85)
        at org.dcache.xrootd.pool.WriteDescriptor.write(WriteDescriptor.java:41)
        at org.dcache.xrootd.pool.XrootdPoolRequestHandler.doOnWrite(XrootdPoolRequestHandler.java:634)
        at org.dcache.xrootd.pool.XrootdPoolRequestHandler.doOnWrite(XrootdPoolRequestHandler.java:104)
```

We can see that finalize is called, but write continues afterward.

I am not sure whether this actually needs to be handled differently, or whether we should just demote the logging of this error to warn, info or even debug.

It does not seem like you can currently prevent write from being called if the channel is closed.

**Comment by alrossi** [comment]
I see that Anupam was the author of the code that uses Preconditions.checkState

```
 checkState(_isWritable, "ChecksumChannel must not be written to after getChecksums");
```

in the three write methods for the ChecksumChannel.   My impression is that this is not really a RuntimeException (a bug), but can indeed occur occasionally if the client misbehaves.

I suggest we change these to

if (!_isWritable) {
   _log.warn("ChecksumChannel cannot be written to after getChecksums has been called.");
}

**Comment by alrossi** [comment]
Or perhaps it needs to be thrown as a specific error and have xrootd send it back to the client.

**Comment by alrossi** [comment]
Deploying rpm with more monitoring.

**Comment by alrossi** [comment]
A second version of

https://rb.dcache.org/r/12391/

Is being tested.   The first version looked good (no exception for a week after deployment).  The second version is a slightly different approach which should achieve the same result.

**Comment by alrossi** [comment]
I'm reopening this issue for two-party copy.

It seems I reached a tentative conclusion that this was a misclassification (it occurs when the client behaves badly).

We are seeing again at PIC when connections are prematurely closed.   

I would suggest we simply suppress the error (demote it).

**Comment by alrossi** [comment]
Then again, this might be fixed inside the post processing ...

**Comment by paulmillar** [comment]
Just to add my 2c-worth.

We have the idea in dCache that files are immutable: once the file is closed it cannot subsequently be modified.

The fetching the checksum should be triggered by the protocol-specific code (the mover) once all data has been accepted.  Doing this "locks" the checksum, so further updates will trigger the error.  This is (arguably) an important safety feature.

The `IllegalStateException` is (IMHO) reasonable: the mover should not be attempting to write any further data once the file has been closed and the checksum has been calculated.  Such behaviour is a bug (in the mover), so throwing a (subclass of) `RuntimeException` seems reasonable to me.

The client can always try to misbehave (I'm reminded of "The Scorpion and the Frog" fable) however, the mover code should handle such malcontent clients "correctly" (the definition of which is protocol-specific).  For example, if the client closes a file and then tried to write to that file, the mover could return an error on the write.

**Comment by alrossi** [comment]
So are you saying this is a Runtime Error or not?   If we return the error to the client, it is not really a bug.

**Comment by alrossi** [comment]
I think the underlying problem is one of synchronization, to be quite honest.   The channel close which occurs releases the mover, triggering the first checksum in the PostProcessing class code.  But the client has not got the message yet, or the last write is still in flight.   So ... the write tries to do so on a channel that already processed the checksum.

I think the bug is similar to the persist-on-close one we fixed.   Something needs to be done internally in xroot to ensure that a late-arriving write from the client does not succeed.   I don't think we can really attribute this to the client (as I originally did).   I think it is in need of a synchronization fix.

**Comment by alrossi** [comment]
(The channel close above, being related to a connection timeout or error of some sort)
